/**
 * Freestyle in-VM daemon builder. Output is a JS string baked into the
 * VmSpec and started by systemd — updates require recreating freestyle VMs.
 *
 * Runs under /opt/bun/bin/bun on every VM (Bun is attached unconditionally
 * in the runner's VmSpec). Uses Bun.serve with web-standard Request/Response
 * and a ReadableStream for SSE.
 *
 * Body wire format: POST bodies are base64-encoded JSON (see
 * parseBase64JsonBody). This is NOT legacy — it's a Cloudflare WAF bypass
 * applied by the mesh server's daemonPost helper to avoid CF triggering on
 * shell commands in /bash etc.
 */

/** Inlined so the runner package stays self-contained (no upward import). */
const PACKAGE_MANAGER_DAEMON_CONFIG: Record<
  string,
  { install: string; runPrefix: string }
> = {
  npm: { install: "npm install", runPrefix: "npm run" },
  pnpm: { install: "pnpm install", runPrefix: "pnpm run" },
  yarn: { install: "yarn install", runPrefix: "yarn run" },
  bun: { install: "bun install", runPrefix: "bun run" },
  deno: { install: "deno install", runPrefix: "deno task" },
};

interface DaemonConfig {
  upstreamPort: string;
  packageManager: string | null;
  pathPrefix: string;
  port: string;
  cloneUrl: string;
  repoName: string;
  proxyPort: number;
  bootstrapScript: string;
  gitUserName: string;
  gitUserEmail: string;
  /** Required, non-empty. Daemon clones with `-b <branch>`. */
  branch: string;
  /**
   * Bearer token required on every `/_decopilot_vm/*` request. Generated
   * per-VM by the runner and persisted alongside state so `resume` can
   * thread the same token on restart. Must be ≥ 32 bytes of entropy.
   */
  daemonToken: string;
}

export function buildDaemonScript(config: DaemonConfig): string {
  const {
    upstreamPort,
    packageManager,
    pathPrefix,
    port,
    cloneUrl,
    repoName,
    proxyPort,
    bootstrapScript,
    gitUserName,
    gitUserEmail,
    branch,
    daemonToken,
  } = config;

  if (!/^\d+$/.test(upstreamPort)) {
    throw new Error(`Invalid upstream port: ${upstreamPort}`);
  }
  if (typeof branch !== "string" || branch.length === 0) {
    throw new Error("DaemonConfig.branch is required and must be non-empty");
  }
  if (typeof daemonToken !== "string" || daemonToken.length < 32) {
    throw new Error(
      "DaemonConfig.daemonToken is required and must be ≥ 32 chars",
    );
  }

  return `// Generated by buildDaemonScript — runs under Bun.
import fs from "node:fs";
import path from "node:path";
import { spawn, spawnSync, execSync } from "node:child_process";
import { timingSafeEqual } from "node:crypto";
const UPSTREAM = "${upstreamPort}";
const UPSTREAM_HOST = "localhost";
const PROXY_PORT = ${proxyPort};
const BOOTSTRAP = ${JSON.stringify(bootstrapScript)};
const MAX_SSE_CLIENTS = 10;
const CLONE_URL = ${JSON.stringify(cloneUrl)};
const REPO_NAME = ${JSON.stringify(repoName)};
const PM = ${JSON.stringify(packageManager)};
const PORT = ${JSON.stringify(port)};
const PATH_PREFIX = ${JSON.stringify(pathPrefix)};
const GIT_USER_NAME = ${JSON.stringify(gitUserName)};
const GIT_USER_EMAIL = ${JSON.stringify(gitUserEmail)};
const BRANCH = ${JSON.stringify(branch)};
const EXPECTED_AUTH = Buffer.from("Bearer " + ${JSON.stringify(daemonToken)}, "utf8");

// Bearer auth for /_decopilot_vm/* — reverse-proxy path stays public (serves
// user's dev server content). timingSafeEqual requires equal-length buffers;
// the length itself leaks nothing useful (scheme + token length are fixed).
function authorized(req) {
  const header = req.headers.get("authorization") || "";
  const received = Buffer.from(header, "utf8");
  if (received.length !== EXPECTED_AUTH.length) return false;
  return timingSafeEqual(received, EXPECTED_AUTH);
}

const APP_ROOT = "/app";
const DECO_UID = 1000;
const DECO_GID = 1000;
const DECO_ENV = Object.assign({}, process.env, { TERM: "xterm-256color", HOME: "/home/deco", LANG: "en_US.UTF-8", LC_ALL: "en_US.UTF-8" });

const PM_CONFIG = ${JSON.stringify(PACKAGE_MANAGER_DAEMON_CONFIG)};

const WELL_KNOWN_STARTERS = ["dev", "start"];

// --- Process-level error handlers (keep daemon alive on unhandled errors) ---
process.on("uncaughtException", (err) => {
  console.error("[daemon] uncaughtException:", err.stack || err.message || err);
});
process.on("unhandledRejection", (reason) => {
  console.error("[daemon] unhandledRejection:", reason);
});

// --- Path safety ---
function safePath(userPath) {
  const resolved = path.resolve(APP_ROOT, userPath);
  if (!resolved.startsWith(APP_ROOT + "/") && resolved !== APP_ROOT) {
    return null;
  }
  return resolved;
}

// --- JSON body parser (base64-encoded payloads) ---
// Callers (mesh server's daemonPost helper) wrap request bodies in base64 to
// avoid Cloudflare WAF triggering on shell commands in /bash etc. We keep
// the contract: base64 → percent-encoded UTF-8 → JSON.parse → object.
async function parseBase64JsonBody(req) {
  const raw = await req.text();
  log("parseBase64JsonBody", "url=" + new URL(req.url).pathname, "rawLength=" + raw.length);
  try {
    const decoded = decodeURIComponent(
      atob(raw).split("").map(function(c) {
        return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
      }).join("")
    );
    const parsed = JSON.parse(decoded);
    log("parseBase64JsonBody", "parsed OK, keys=" + Object.keys(parsed).join(","));
    return parsed;
  } catch (e) {
    log("parseBase64JsonBody", "FAILED to parse", "error=" + e.message, "raw=" + raw.slice(0, 1000));
    throw new Error("Failed to parse body: " + e.message + " | raw=" + raw.slice(0, 200));
  }
}

// --- Logging ---
function log(...args) {
  const ts = new Date().toISOString();
  const msg = "[daemon] " + ts + " " + args.join(" ");
  console.log(msg);
  broadcastChunk("daemon", msg + "\\r\\n");
}

// --- SSE state ---
// sseClients holds ReadableStreamDefaultController objects (Bun-native SSE).
const sseClients = new Set();
let lastStatus = { ready: false, htmlSupport: false };

const textEncoder = new TextEncoder();

function sseFormat(eventName, payload) {
  return textEncoder.encode(
    "event: " + eventName + "\\ndata: " + payload + "\\n\\n",
  );
}

// --- Process state ---
const children = {};
const replayBuffers = { setup: "", daemon: "" };
const REPLAY_BYTES = 4096;
let setupDone = false;
let setupRunning = false;
let discoveredScripts = null;
let lastBranchStatus = null;
let branchStatusTimer = null;
let branchStatusWatcher = null;

function broadcastChunk(source, data) {
  if (!data) return;
  if (!replayBuffers[source]) replayBuffers[source] = "";
  const buf = replayBuffers[source] + data;
  replayBuffers[source] = buf.length > REPLAY_BYTES ? buf.slice(buf.length - REPLAY_BYTES) : buf;
  const payload = JSON.stringify({ source: source, data: data });
  const bytes = sseFormat("log", payload);
  for (const c of sseClients) {
    try { c.enqueue(bytes); } catch (e) {}
  }
}

function broadcastEvent(eventName, data) {
  const bytes = sseFormat(eventName, JSON.stringify(data));
  for (const c of sseClients) {
    try { c.enqueue(bytes); } catch (e) {}
  }
}

// Run git with an argv array via spawnSync. Avoids shell parsing quirks in
// Bun's execSync and surfaces the child's stderr on failure (Bun's execSync
// drops stderr when thrown). asUser=false runs as whoever the daemon is
// (root under systemd) — used for system-level config like safe.directory.
function gitSync(args, opts) {
  const asUser = opts && opts.asUser === false ? false : true;
  const spawnOpts = {
    cwd: (opts && opts.cwd) || APP_ROOT,
    env: DECO_ENV,
    stdio: ["ignore", "pipe", "pipe"],
    encoding: "utf-8",
  };
  if (asUser) { spawnOpts.uid = DECO_UID; spawnOpts.gid = DECO_GID; }
  const res = spawnSync("git", args, spawnOpts);
  if (res.error) {
    const err = new Error("git " + args.join(" ") + ": " + res.error.message);
    err.stderr = String(res.stderr || "");
    throw err;
  }
  if (res.status !== 0) {
    const err = new Error("git " + args.join(" ") + " exited " + res.status + (res.stderr ? ": " + String(res.stderr).trim() : ""));
    err.stderr = String(res.stderr || "");
    err.status = res.status;
    throw err;
  }
  return String(res.stdout || "").trim();
}

function computeBranchStatus() {
  const exec = (args) => {
    try { return gitSync(args); } catch (e) { return ""; }
  };
  const refExists = (ref) => exec(["rev-parse", "--verify", "--quiet", ref]).length > 0;
  try {
    const branch = exec(["rev-parse", "--abbrev-ref", "HEAD"]);
    if (!branch || branch === "HEAD") return null;
    let base = exec(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"]);
    if (base.startsWith("origin/")) base = base.slice("origin/".length);
    if (!base) base = "main";
    const dirty = exec(["status", "--porcelain=v1"]).length > 0;

    // origin/<branch> may not exist (not fetched yet, or local-only). Fall back
    // to HEAD on the "branch" side when it's missing — we can still measure
    // ahead-of-base that way; unpushed stays 0 because we can't see a diff.
    const branchRef = refExists("origin/" + branch) ? "origin/" + branch : "HEAD";
    const unpushed = branchRef === "origin/" + branch
      ? Number(exec(["rev-list", "--count", "origin/" + branch + "..HEAD"]) || "0")
      : 0;

    let aheadOfBase = 0, behindBase = 0;
    if (refExists("origin/" + base)) {
      const lrcount = exec(["rev-list", "--left-right", "--count", "origin/" + base + "..." + branchRef]);
      const m = lrcount.match(/^(\\d+)\\s+(\\d+)$/);
      if (m) { behindBase = Number(m[1]); aheadOfBase = Number(m[2]); }
    }
    // Current head sha — used by the frontend to detect branch advances
    // past a merged PR's head.
    const headSha = exec(["rev-parse", branchRef]);
    return { branch: branch, base: base, workingTreeDirty: dirty, unpushed: unpushed, aheadOfBase: aheadOfBase, behindBase: behindBase, headSha: headSha };
  } catch (e) {
    log("branch-status compute failed:", e && e.message ? e.message : e);
    return null;
  }
}

function emitBranchStatus() {
  const next = computeBranchStatus();
  if (!next) return;
  if (lastBranchStatus && JSON.stringify(lastBranchStatus) === JSON.stringify(next)) return;
  lastBranchStatus = next;
  broadcastEvent("branch-status", Object.assign({ type: "branch-status" }, next));
}

function scheduleBranchStatusRefresh() {
  if (branchStatusTimer) return;
  branchStatusTimer = setTimeout(() => {
    branchStatusTimer = null;
    emitBranchStatus();
  }, 250);
}

function watchGitDir() {
  if (branchStatusWatcher) return;
  const gitDir = APP_ROOT + "/.git";
  try {
    branchStatusWatcher = fs.watch(gitDir, { recursive: true }, () => {
      scheduleBranchStatusRefresh();
    });
    log("branch-status: watching " + gitDir);
  } catch (e) {
    log("branch-status: fs.watch failed, falling back to polling:", e && e.message ? e.message : e);
    setInterval(emitBranchStatus, 5000);
  }
}

function runProcess(source, cmd, label) {
  if (children[source]) {
    const old = children[source];
    log("killing", source, "pid=" + old.pid);
    // Detach stdout/stderr listeners first so the old child's trailing
    // output (after we start the new one but before the kernel reaps it)
    // doesn't interleave with the new child's stream under the same source.
    try {
      if (old.stdout) old.stdout.removeAllListeners("data");
      if (old.stderr) old.stderr.removeAllListeners("data");
    } catch (e) {}
    try { old.kill("SIGKILL"); } catch (e) {}
    children[source] = null;
  }
  if (!replayBuffers[source]) replayBuffers[source] = "";
  broadcastChunk(source, label + "\\r\\n");
  const child = spawn("script", ["-q", "-c", cmd, "/dev/null"], {
    stdio: ["ignore", "pipe", "pipe"],
    uid: DECO_UID,
    gid: DECO_GID,
    env: DECO_ENV,
  });
  children[source] = child;
  log("spawned", source, "pid=" + child.pid);
  broadcastEvent("processes", { type: "processes", active: Object.keys(children).filter(k => children[k] !== null) });
  child.stdout.on("data", (chunk) => {
    broadcastChunk(source, chunk.toString("utf-8"));
  });
  child.stderr.on("data", (chunk) => {
    broadcastChunk(source, chunk.toString("utf-8"));
  });
  child.on("error", (err) => {
    log("spawn error", source, err && err.message ? err.message : String(err));
    if (children[source] === child) {
      children[source] = null;
      broadcastEvent("processes", { type: "processes", active: Object.keys(children).filter(k => children[k] !== null) });
    }
  });
  child.on("close", (code) => {
    log(source, "exited", "pid=" + child.pid, "code=" + code);
    if (children[source] === child) children[source] = null;
    broadcastEvent("processes", { type: "processes", active: Object.keys(children).filter(k => children[k] !== null) });
  });
  return child;
}

function discoverScripts() {
  if (!PM) return;
  let scripts = {};
  try {
    if (PM === "deno") {
      for (const f of ["deno.json", "deno.jsonc"]) {
        try {
          const raw = fs.readFileSync("/app/" + f, "utf-8");
          const parsed = JSON.parse(raw);
          scripts = parsed.tasks || {};
          break;
        } catch (e) { /* file not found or parse error, try next */ }
      }
    } else {
      try {
        const raw = fs.readFileSync("/app/package.json", "utf-8");
        const parsed = JSON.parse(raw);
        scripts = parsed.scripts || {};
      } catch (e) { /* no package.json */ }
    }
  } catch (e) {
    log("script discovery failed:", e.message);
  }
  const scriptNames = Object.keys(scripts);
  discoveredScripts = scriptNames;
  log("discovered scripts:", scriptNames.join(", ") || "(none)");
  broadcastEvent("scripts", { type: "scripts", scripts: scriptNames });

  // Freestyle has no /_daemon/dev/start (systemd handles it), so we auto-kick
  // the first well-known starter here to match Docker's behavior.
  const pmConfig = PM_CONFIG[PM];
  if (pmConfig) {
    const autoStart = WELL_KNOWN_STARTERS.find((s) => scriptNames.includes(s));
    if (autoStart) {
      const cmd = PATH_PREFIX + "cd /app && HOST=0.0.0.0 HOSTNAME=0.0.0.0 PORT=" + PORT + " " + pmConfig.runPrefix + " " + autoStart;
      const label = "$ " + pmConfig.runPrefix + " " + autoStart;
      log("auto-start", autoStart);
      runProcess(autoStart, cmd, label);
    }
  }
}

function runSetup() {
  // Clone the repo's default branch, then switch to BRANCH — fetching it
  // from origin when the remote has it, or creating it locally off default
  // when it does not. This keeps newly-generated deco/* branches
  // working without requiring the caller to push first.
  // BRANCH is always non-empty — validated at daemon build time.
  const branchNameOk = (b) => /^[A-Za-z0-9._/-]+$/.test(b) && !b.startsWith("-");
  if (!branchNameOk(BRANCH)) {
    broadcastChunk("setup", "\\r\\nInvalid branch name: " + BRANCH + "\\r\\n");
    log("invalid branch name: " + BRANCH);
    return;
  }

  // Re-entry guard: reject overlapping calls (boot auto-setup + HTTP exec/setup,
  // or two HTTP exec/setup calls in quick succession). Cleared in every
  // terminal branch below so a failed run can be retried.
  if (setupRunning) {
    log("runSetup ignored: setup already running");
    broadcastChunk("setup", "\\r\\nSetup already running; ignoring re-entry\\r\\n");
    return;
  }
  setupRunning = true;

  // Mark setup complete + side effects; call from every terminal branch.
  const finish = (success) => {
    setupRunning = false;
    setupDone = true;
    emitBranchStatus();
    watchGitDir();
    if (success) {
      log("setup complete, discovering scripts");
      discoverScripts();
    }
  };

  // Second phase after clone (or resume when /app/.git already exists): set
  // git identity, resolve BRANCH, then run install. Hoisted into a named
  // function so both paths can reuse it.
  function proceedAfterClone() {
    // Tell git to trust /app regardless of who runs it. git 2.35+ rejects
    // repos whose working tree is owned by a different uid than the caller
    // ("dubious ownership"), which bites us when any future refactor runs
    // git as a different user than /app's owner. System-level config, no
    // uid drop — we're root here.
    try {
      gitSync(["config", "--system", "--add", "safe.directory", APP_ROOT], { asUser: false });
    } catch (e) {
      log("git safe.directory setup failed:", e.message);
    }

    // Configure git identity.
    try {
      gitSync(["config", "user.name", GIT_USER_NAME]);
      gitSync(["config", "user.email", GIT_USER_EMAIL]);
    } catch (e) {
      log("git identity setup failed:", e.message, e.stderr || "");
      broadcastChunk("setup", "\\r\\nWarning: could not set up git identity\\r\\n");
    }

    // Resolve BRANCH: fetch from remote when it exists there, otherwise
    // create locally off the default branch we just cloned.
    //
    // The refspec form +refs/heads/BRANCH:refs/remotes/origin/BRANCH creates
    // the remote-tracking ref in one step so branch-status can diff against
    // origin/<branch>. The paired local-branch copy happens with a second
    // fetch using the BRANCH:BRANCH refspec below.
    let branchOnRemote = false;
    try {
      gitSync(["fetch", "origin", "+refs/heads/" + BRANCH + ":refs/remotes/origin/" + BRANCH]);
      gitSync(["fetch", "origin", BRANCH + ":" + BRANCH]);
      branchOnRemote = true;
    } catch (e) {
      // Branch doesn't exist on remote — create it locally below.
      log("fetch origin " + BRANCH + " failed (branch likely absent remote): " + (e && e.message ? e.message : e));
    }

    // On resume, the branch may already be checked out locally. Try a
    // plain checkout first (no-ops on the current branch, switches if
    // present locally); fall back to checkout -b when the local branch
    // doesn't exist yet.
    try {
      if (branchOnRemote) {
        gitSync(["checkout", BRANCH]);
        broadcastChunk("setup", "\\r\\n$ git checkout " + BRANCH + " (from origin)\\r\\n");
        log("checked out " + BRANCH + " from remote");
      } else {
        try {
          gitSync(["checkout", BRANCH]);
          broadcastChunk("setup", "\\r\\n$ git checkout " + BRANCH + " (existing local)\\r\\n");
          log("checked out existing local branch " + BRANCH);
        } catch (_e) {
          gitSync(["checkout", "-b", BRANCH]);
          broadcastChunk("setup", "\\r\\n$ git checkout -b " + BRANCH + " (new local)\\r\\n");
          log("created local branch " + BRANCH + " off default");
        }
      }
    } catch (e) {
      log("git branch setup failed:", e.message, e.stderr || "");
      broadcastChunk("setup", "\\r\\nWarning: could not set up branch " + BRANCH + "\\r\\n");
    }

    if (!PM) {
      log("setup complete (clone only, no package manager)");
      finish(false);
      return;
    }
    // Run install in the same "setup" stream
    const pmConfig = PM_CONFIG[PM];
    if (!pmConfig) {
      finish(false);
      return;
    }
    const corepackSetup = "export COREPACK_ENABLE_DOWNLOAD_PROMPT=0 && corepack enable && ";
    const installCmd = PATH_PREFIX + "cd " + APP_ROOT + " && " + corepackSetup + pmConfig.install;
    const installLabel = "$ " + pmConfig.install;
    broadcastChunk("setup", "\\r\\n" + installLabel + "\\r\\n");

    const installChild = spawn("script", ["-q", "-c", installCmd, "/dev/null"], {
      stdio: ["ignore", "pipe", "pipe"],
      uid: DECO_UID,
      gid: DECO_GID,
      env: DECO_ENV,
    });
    log("spawned setup (install) pid=" + installChild.pid);
    installChild.stdout.on("data", (chunk) => broadcastChunk("setup", chunk.toString("utf-8")));
    installChild.stderr.on("data", (chunk) => broadcastChunk("setup", chunk.toString("utf-8")));
    installChild.on("error", (err) => {
      log("spawn error install", err && err.message ? err.message : String(err));
      broadcastChunk("setup", "\\r\\nSpawn failed: " + ((err && err.message) || err) + "\\r\\n");
      setupRunning = false;
      setupDone = true;
      emitBranchStatus();
      watchGitDir();
    });
    installChild.on("close", (installCode) => {
      log("install exited code=" + installCode);
      if (installCode === 0) {
        finish(true);
      } else {
        setupRunning = false;
        setupDone = true;
        emitBranchStatus();
        watchGitDir();
        broadcastChunk("setup", "\\r\\nInstall failed with exit code " + installCode + "\\r\\n");
      }
    });
  }

  // Resume-on-restart: if /app/.git already exists, the repo is cloned and
  // we jump straight to the post-clone logic. Without this, git clone into
  // a non-empty directory fails and setup hangs forever after a daemon
  // crash during a previous setup run.
  let gitDirExists = false;
  try {
    gitDirExists = fs.existsSync(APP_ROOT + "/.git");
  } catch (_e) {
    gitDirExists = false;
  }
  if (gitDirExists) {
    log("resuming setup: " + APP_ROOT + "/.git exists, skipping clone");
    broadcastChunk("setup", "$ (resuming setup; " + APP_ROOT + " already cloned)\\r\\n");
    proceedAfterClone();
    return;
  }

  const cloneCmd = "git clone --depth 1 " + CLONE_URL + " " + APP_ROOT;
  const cloneLabel = "$ git clone --depth 1 " + REPO_NAME + " " + APP_ROOT;
  broadcastChunk("setup", cloneLabel + "\\r\\n");

  const child = spawn("script", ["-q", "-c", cloneCmd, "/dev/null"], {
    stdio: ["ignore", "pipe", "pipe"],
    uid: DECO_UID,
    gid: DECO_GID,
    env: DECO_ENV,
  });
  log("spawned setup (clone) pid=" + child.pid);
  child.stdout.on("data", (chunk) => broadcastChunk("setup", chunk.toString("utf-8")));
  child.stderr.on("data", (chunk) => broadcastChunk("setup", chunk.toString("utf-8")));
  child.on("error", (err) => {
    log("spawn error clone", err && err.message ? err.message : String(err));
    broadcastChunk("setup", "\\r\\nSpawn failed: " + ((err && err.message) || err) + "\\r\\n");
    setupRunning = false;
  });
  child.on("close", (code) => {
    log("clone exited code=" + code);
    if (code !== 0) {
      setupRunning = false;
      broadcastChunk("setup", "\\r\\nClone failed with exit code " + code + "\\r\\n");
      return;
    }
    proceedAfterClone();
  });
}

// --- Liveness probe ---
let probeCount = 0;
const FAST_PROBE_MS = 3000;
const SLOW_PROBE_MS = 30000;
const FAST_PROBE_LIMIT = 20;

async function probeUpstream() {
  const prevReady = lastStatus.ready;
  try {
    const res = await fetch(
      "http://" + UPSTREAM_HOST + ":" + UPSTREAM + "/",
      { method: "HEAD", signal: AbortSignal.timeout(5000) },
    );
    const ct = (res.headers.get("content-type") || "").toLowerCase();
    lastStatus = {
      ready: res.status >= 200 && res.status < 400,
      htmlSupport: ct.includes("text/html"),
    };
    if (lastStatus.ready !== prevReady) {
      log("upstream", lastStatus.ready ? "UP" : "DOWN", "status=" + res.status);
    }
  } catch (e) {
    if (prevReady) log("upstream DOWN (error)", e.message || String(e));
    lastStatus = { ready: false, htmlSupport: false };
  }

  probeCount++;
  const nextDelay = probeCount < FAST_PROBE_LIMIT ? FAST_PROBE_MS : SLOW_PROBE_MS;
  setTimeout(probeUpstream, nextDelay);
}

setTimeout(probeUpstream, 1000);

// --- File operation handlers (Bun-native: Request → Response) ---

async function handleRead(req) {
  let body;
  try { body = await parseBase64JsonBody(req); }
  catch (e) { return jsonResponse({ error: e.message }, 400); }

  const filePath = safePath(body.path || "");
  if (!filePath) return jsonResponse({ error: "Path escapes /app" }, 400);

  let stat;
  try { stat = fs.statSync(filePath); }
  catch { return jsonResponse({ error: "File not found: " + body.path }, 400); }
  if (stat.isDirectory()) return jsonResponse({ error: "Path is a directory" }, 400);

  // Binary detection: check first 8KB for null bytes
  const fd = fs.openSync(filePath, "r");
  const probe = Buffer.alloc(Math.min(8192, stat.size));
  fs.readSync(fd, probe, 0, probe.length, 0);
  fs.closeSync(fd);
  if (probe.includes(0)) return jsonResponse({ error: "File appears to be binary" }, 400);

  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    const lines = raw.split("\\n");
    const offset = Math.max(1, body.offset || 1);
    const limit = body.limit || 2000;
    const slice = lines.slice(offset - 1, offset - 1 + limit);
    const numbered = slice.map((line, i) => (offset + i) + "\\t" + line).join("\\n");
    return jsonResponse({ content: numbered, lineCount: lines.length });
  } catch (e) {
    return jsonResponse({ error: e.message }, 500);
  }
}

async function handleWrite(req) {
  let body;
  try { body = await parseBase64JsonBody(req); }
  catch (e) { return jsonResponse({ error: e.message }, 400); }

  if (typeof body.content !== "string") return jsonResponse({ error: "content is required" }, 400);
  const filePath = safePath(body.path || "");
  if (!filePath) return jsonResponse({ error: "Path escapes /app" }, 400);

  try {
    const dir = path.dirname(filePath);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(filePath, body.content, "utf-8");
    return jsonResponse({ ok: true, bytesWritten: Buffer.byteLength(body.content, "utf-8") });
  } catch (e) {
    return jsonResponse({ error: e.message }, 500);
  }
}

async function handleEdit(req) {
  let body;
  try { body = await parseBase64JsonBody(req); }
  catch (e) { return jsonResponse({ error: e.message }, 400); }

  const filePath = safePath(body.path || "");
  if (!filePath) return jsonResponse({ error: "Path escapes /app" }, 400);
  if (!body.old_string || typeof body.old_string !== "string") return jsonResponse({ error: "old_string is required" }, 400);
  if (typeof body.new_string !== "string") return jsonResponse({ error: "new_string is required" }, 400);
  if (body.old_string === body.new_string) return jsonResponse({ error: "old_string and new_string must differ" }, 400);

  let content;
  try { content = fs.readFileSync(filePath, "utf-8"); }
  catch { return jsonResponse({ error: "File not found: " + body.path }, 400); }

  const replaceAll = body.replace_all === true;
  const count = content.split(body.old_string).length - 1;
  if (count === 0) return jsonResponse({ error: "old_string not found in file" }, 400);
  if (!replaceAll && count > 1) return jsonResponse({ error: "old_string found " + count + " times. Use replace_all or provide more context to make it unique." }, 400);

  try {
    const updated = replaceAll ? content.replaceAll(body.old_string, body.new_string) : content.replace(body.old_string, body.new_string);
    fs.writeFileSync(filePath, updated, "utf-8");
    return jsonResponse({ ok: true, replacements: replaceAll ? count : 1 });
  } catch (e) {
    return jsonResponse({ error: e.message }, 500);
  }
}

async function handleGrep(req) {
  let body;
  try { body = await parseBase64JsonBody(req); }
  catch (e) { return jsonResponse({ error: e.message }, 400); }

  if (!body.pattern) return jsonResponse({ error: "pattern is required" }, 400);

  const searchPath = body.path ? safePath(body.path) : APP_ROOT;
  if (!searchPath) return jsonResponse({ error: "Path escapes /app" }, 400);

  const args = [];
  const mode = body.output_mode || "files";
  if (mode === "files") args.push("--files-with-matches");
  else if (mode === "count") args.push("--count");
  else args.push("--line-number");

  if (body.ignore_case) args.push("-i");
  if (body.context && mode === "content") args.push("-C", String(body.context));
  if (body.glob) args.push("--glob", body.glob);
  args.push("--", body.pattern, searchPath);

  const limit = body.limit || 250;
  const child = spawn("rg", args, { cwd: APP_ROOT, stdio: ["ignore", "pipe", "pipe"], uid: DECO_UID, gid: DECO_GID });
  let stdout = "";
  let lineCount = 0;
  let truncated = false;
  child.stdout.on("data", (chunk) => {
    if (truncated) return;
    const text = chunk.toString("utf-8");
    const lines = text.split("\\n");
    for (const line of lines) {
      if (lineCount >= limit) {
        // Kill rg once we've collected enough — otherwise rg keeps emitting
        // to stdout until the OS pipe buffer fills and it blocks in write(),
        // and the daemon's close-promise never resolves.
        truncated = true;
        try { child.kill("SIGTERM"); } catch (e) {}
        break;
      }
      if (line) { stdout += (stdout ? "\\n" : "") + line; lineCount++; }
    }
  });
  let stderr = "";
  child.stderr.on("data", (chunk) => { stderr += chunk.toString("utf-8"); });

  const code = await new Promise((resolve) => {
    child.on("close", (c) => resolve(c));
    child.on("error", (err) => {
      log("spawn error grep", err && err.message ? err.message : String(err));
      resolve(-1);
    });
  });
  // rg exits 1 when no matches found — not an error. When we SIGTERM above,
  // code is typically null (signal termination) which satisfies !(code > 1)
  // and falls through to the success response with the already-collected
  // results.
  if (code !== null && code > 1) return jsonResponse({ error: stderr || "rg failed with code " + code }, 500);
  return jsonResponse({ results: stdout, matchCount: lineCount });
}

async function handleGlob(req) {
  let body;
  try { body = await parseBase64JsonBody(req); }
  catch (e) { return jsonResponse({ error: e.message }, 400); }

  if (!body.pattern) return jsonResponse({ error: "pattern is required" }, 400);

  const searchPath = body.path ? safePath(body.path) : APP_ROOT;
  if (!searchPath) return jsonResponse({ error: "Path escapes /app" }, 400);

  const child = spawn("rg", ["--files", "--glob", body.pattern, searchPath], { cwd: APP_ROOT, stdio: ["ignore", "pipe", "pipe"], uid: DECO_UID, gid: DECO_GID });
  let stdout = "";
  child.stdout.on("data", (chunk) => { stdout += chunk.toString("utf-8"); });
  let stderr = "";
  child.stderr.on("data", (chunk) => { stderr += chunk.toString("utf-8"); });

  const code = await new Promise((resolve) => {
    child.on("close", (c) => resolve(c));
    child.on("error", (err) => {
      log("spawn error glob", err && err.message ? err.message : String(err));
      resolve(-1);
    });
  });
  if (code !== null && code > 1) return jsonResponse({ error: stderr || "rg failed with code " + code }, 500);
  const files = stdout.split("\\n").filter(Boolean).slice(0, 1000).map(f => {
    return f.startsWith(APP_ROOT + "/") ? f.slice(APP_ROOT.length + 1) : f;
  });
  return jsonResponse({ files: files });
}

async function handleBash(req) {
  let body;
  try { body = await parseBase64JsonBody(req); }
  catch (e) { return jsonResponse({ error: e.message }, 400); }

  if (!body.command || typeof body.command !== "string")
    return jsonResponse({ error: "command is required" }, 400);

  const timeout = Math.min(body.timeout || 30000, 120000);
  const child = spawn("bash", ["-c", body.command], {
    cwd: APP_ROOT,
    stdio: ["ignore", "pipe", "pipe"],
    uid: DECO_UID,
    gid: DECO_GID,
    env: DECO_ENV,
  });

  let stdout = "";
  let stderr = "";
  let killed = false;
  child.stdout.on("data", (chunk) => { stdout += chunk.toString("utf-8"); });
  child.stderr.on("data", (chunk) => { stderr += chunk.toString("utf-8"); });

  const timer = setTimeout(() => {
    killed = true;
    try { child.kill("SIGKILL"); } catch (e) {}
  }, timeout);

  const exitCode = await new Promise((resolve) => {
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve(killed ? -1 : (code ?? 1));
    });
    child.on("error", (err) => {
      clearTimeout(timer);
      log("spawn error bash", err && err.message ? err.message : String(err));
      // Surface the error in stderr so the caller has context.
      stderr += (stderr ? "\\n" : "") + "spawn error: " + (err && err.message ? err.message : String(err));
      resolve(-1);
    });
  });
  return jsonResponse({ stdout: stdout, stderr: stderr, exitCode: exitCode });
}

// --- Bun-native helpers ---
function jsonResponse(body, status) {
  return new Response(JSON.stringify(body), {
    status: status ?? 200,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
    },
  });
}

function handleEvents() {
  if (sseClients.size >= MAX_SSE_CLIENTS) {
    log("SSE rejected (max clients)");
    return new Response("Too many connections", {
      status: 429,
      headers: { "Access-Control-Allow-Origin": "*" },
    });
  }
  let controller;
  let keepAliveTimer;
  const stream = new ReadableStream({
    start(c) {
      controller = c;
      // Replay state first — enqueue snapshots BEFORE adding this controller
      // to sseClients so concurrent broadcastChunk / broadcastEvent calls
      // don't interleave live output inside the replay window. Without the
      // ordering, a live log line can land between the replay-status and
      // replay-log frames and the client sees events out of order (and may
      // see the same line twice — once in the log replay buffer, once live).
      c.enqueue(sseFormat("status", JSON.stringify({ type: "status", ...lastStatus })));
      for (const source of Object.keys(replayBuffers)) {
        const buf = replayBuffers[source];
        if (buf && buf.length > 0) {
          c.enqueue(sseFormat("log", JSON.stringify({ source: source, data: buf })));
        }
      }
      if (discoveredScripts) {
        c.enqueue(sseFormat("scripts", JSON.stringify({ type: "scripts", scripts: discoveredScripts })));
      }
      const active = Object.keys(children).filter((k) => children[k] !== null);
      c.enqueue(sseFormat("processes", JSON.stringify({ type: "processes", active: active })));
      if (lastBranchStatus) {
        c.enqueue(sseFormat("branch-status", JSON.stringify(Object.assign({ type: "branch-status" }, lastBranchStatus))));
      }

      // NOW register for live broadcasts. The log() below also broadcasts,
      // but the controller receives it only as a fresh live event (not as
      // part of the replay buffer we just flushed).
      sseClients.add(c);
      log("SSE connect, clients=" + sseClients.size);

      keepAliveTimer = setInterval(() => {
        try {
          c.enqueue(sseFormat("status", JSON.stringify({ type: "status", ...lastStatus })));
        } catch (e) {
          clearInterval(keepAliveTimer);
          sseClients.delete(c);
        }
      }, 15000);
    },
    cancel() {
      clearInterval(keepAliveTimer);
      sseClients.delete(controller);
      log("SSE disconnect, clients=" + sseClients.size);
    },
  });

  return new Response(stream, {
    status: 200,
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      "Connection": "keep-alive",
      "Access-Control-Allow-Origin": "*",
      "X-Accel-Buffering": "no",
      "Content-Encoding": "identity",
    },
  });
}

function handleExec(name) {
  if (!name) return jsonResponse({ error: "missing script name" }, 400);
  if (name === "setup") {
    if (setupRunning) {
      log("exec setup rejected: setup already running");
      return jsonResponse({ error: "setup already running" }, 409);
    }
    log("exec setup");
    runSetup();
    return jsonResponse({ ok: true });
  }
  if (!PM || !setupDone) {
    log("exec rejected: setup not done or no package manager");
    return jsonResponse({ error: "setup not complete" }, 400);
  }
  const pmConfig = PM_CONFIG[PM];
  if (!pmConfig) return jsonResponse({ error: "unknown package manager" }, 400);
  const cmd =
    PATH_PREFIX +
    "cd /app && HOST=0.0.0.0 HOSTNAME=0.0.0.0 PORT=" +
    PORT +
    " " +
    pmConfig.runPrefix +
    " " +
    name;
  const label = "$ " + pmConfig.runPrefix + " " + name;
  log("exec", name);
  runProcess(name, cmd, label);
  return jsonResponse({ ok: true });
}

function handleKill(name) {
  if (!name) return jsonResponse({ error: "missing script name" }, 400);
  const child = children[name];
  if (!child) return jsonResponse({ error: "not running" }, 400);
  try { child.kill("SIGTERM"); } catch (e) {}
  // Escalate to SIGKILL if the child ignores SIGTERM (buggy runners,
  // synchronous loops, etc.) so a stuck process can't block subsequent
  // runProcess calls that rely on children[source] being nulled out.
  const killer = setTimeout(() => {
    if (children[name] === child) {
      log("SIGKILL escalation", name);
      try { child.kill("SIGKILL"); } catch (e) {}
    }
  }, 3000);
  child.on("close", () => clearTimeout(killer));
  return jsonResponse({ ok: true });
}

async function handleProxy(req) {
  const url = new URL(req.url);
  const target =
    "http://" + UPSTREAM_HOST + ":" + UPSTREAM + url.pathname + url.search;

  const outHeaders = new Headers(req.headers);
  outHeaders.delete("accept-encoding");
  outHeaders.delete("host");
  outHeaders.delete("transfer-encoding");
  outHeaders.delete("content-length");

  let upstream;
  try {
    const init = { method: req.method, headers: outHeaders, redirect: "manual", signal: AbortSignal.timeout(60000) };
    if (req.method !== "GET" && req.method !== "HEAD") {
      init.body = await req.arrayBuffer();
    }
    upstream = await fetch(target, init);
  } catch (e) {
    log("proxy error", req.method, url.pathname, e.message || String(e));
    const msg = (e.message || String(e));
    const connErr = /ECONNREFUSED|ECONNRESET|ECONNABORTED|fetch failed|Unable to connect|TimeoutError|timed out/i.test(msg);
    if (url.pathname === "/" && connErr) {
      return new Response(
        '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Starting...</title><style>body{font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;background:#fafafa;color:#555}div{text-align:center}p{margin-top:8px;font-size:14px;color:#999}</style></head><body><div><h3>Server is starting\\u2026</h3><p>This page will refresh automatically.</p></div><script>setTimeout(function(){window.location.reload()},1000)</script></body></html>',
        {
          status: 503,
          headers: {
            "Content-Type": "text/html; charset=utf-8",
            "Retry-After": "1",
            "Access-Control-Allow-Origin": "*",
          },
        },
      );
    }
    return jsonResponse({ error: "proxy error: " + msg }, 502);
  }

  const respHeaders = new Headers(upstream.headers);
  respHeaders.delete("x-frame-options");
  respHeaders.delete("content-security-policy");
  respHeaders.delete("content-encoding");

  const ct = (upstream.headers.get("content-type") || "").toLowerCase();
  if (ct.includes("text/html")) {
    respHeaders.delete("content-length");
    let html = await upstream.text();
    const idx = html.lastIndexOf("</body>");
    if (idx !== -1) {
      html = html.slice(0, idx) + BOOTSTRAP + html.slice(idx);
    } else {
      html += BOOTSTRAP;
    }
    return new Response(html, { status: upstream.status, headers: respHeaders });
  }
  return new Response(upstream.body, {
    status: upstream.status,
    headers: respHeaders,
  });
}

// --- HTTP server ---
Bun.serve({
  port: PROXY_PORT,
  hostname: "0.0.0.0",
  // SSE streams can run a long time; disable the default idle timeout.
  idleTimeout: 0,
  async fetch(req) {
    const url = new URL(req.url);
    const pathname = url.pathname;

    if (!pathname.startsWith("/_decopilot_vm/")) {
      log("proxy", req.method, pathname);
    }

    // Bearer required on every /_decopilot_vm/* route except CORS preflight.
    // Reverse-proxy path below stays public (iframe needs unauth dev-server).
    if (
      pathname.startsWith("/_decopilot_vm/") &&
      req.method !== "OPTIONS" &&
      !authorized(req)
    ) {
      return jsonResponse({ error: "unauthorized" }, 401);
    }

    // --- SSE endpoint (Bun-native) ---
    if (pathname === "/_decopilot_vm/events" && req.method === "GET") {
      return handleEvents();
    }

    // --- File operations (Bun-native Request → Response) ---
    if (req.method === "POST" && pathname === "/_decopilot_vm/read")
      return handleRead(req);
    if (req.method === "POST" && pathname === "/_decopilot_vm/write")
      return handleWrite(req);
    if (req.method === "POST" && pathname === "/_decopilot_vm/edit")
      return handleEdit(req);
    if (req.method === "POST" && pathname === "/_decopilot_vm/grep")
      return handleGrep(req);
    if (req.method === "POST" && pathname === "/_decopilot_vm/glob")
      return handleGlob(req);
    if (req.method === "POST" && pathname === "/_decopilot_vm/bash")
      return handleBash(req);

    // --- Exec/kill ---
    if (req.method === "POST" && pathname.startsWith("/_decopilot_vm/exec/")) {
      return handleExec(pathname.slice("/_decopilot_vm/exec/".length));
    }
    if (req.method === "POST" && pathname.startsWith("/_decopilot_vm/kill/")) {
      return handleKill(pathname.slice("/_decopilot_vm/kill/".length));
    }

    // --- Scripts + OPTIONS + catch-all under /_decopilot_vm/ ---
    if (req.method === "GET" && pathname === "/_decopilot_vm/scripts") {
      return jsonResponse({ scripts: discoveredScripts || [] });
    }
    if (req.method === "OPTIONS" && pathname.startsWith("/_decopilot_vm/")) {
      return new Response(null, {
        status: 204,
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Allow-Methods": "GET, POST",
          "Access-Control-Allow-Headers": "Content-Type, Accept, Cache-Control, Authorization",
        },
      });
    }
    if (pathname.startsWith("/_decopilot_vm/")) {
      log("unmatched daemon route", req.method, pathname);
      return jsonResponse({ error: "Not found: " + pathname }, 404);
    }

    // --- Reverse proxy to upstream (Bun-native fetch) ---
    return handleProxy(req);
  },
});

// Auto-start setup on daemon boot
log("starting setup: cloning " + REPO_NAME);
runSetup();
`;
}
