{{- if or .Values.autoscaling.enabled (gt (int (default 1 .Values.replicaCount)) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chart-deco-studio.fullname" . }}
  labels:
    {{- include "chart-deco-studio.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "chart-deco-studio.selectorLabels" . | nindent 6 }}
{{- end }}
