// Auto-generated from capy.json - do not edit manually
export type Segment = { text: string; color: string | null };
export const CAPY_FRAMES: Segment[][][] = [
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▄▀▄░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████■▄■░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▀▄▀░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████■▀■░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▄▀▄░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▀■▀░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▀▄▀░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████■▄■░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "███████████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▄▀▄░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "███████████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████████", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▄▀▄░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "███████████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▄▀▄░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▄▀▄░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
  [
    [
      { text: "       ", color: null },
      { text: "▄▄", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▄▄▄", color: "#5f3800" },
    ],
    [
      { text: "      ", color: null },
      { text: "█░▀█████████▄", color: "#875f00" },
    ],
    [
      { text: "     ", color: null },
      { text: "█████▀▀████", color: "#875f00" },
      { text: "███▄", color: "#5f3800" },
    ],
    [
      { text: "    ", color: null },
      { text: "███████▄▄██", color: "#875f00" },
      { text: "███▐█", color: "#5f3800" },
    ],
    [
      { text: "  ", color: null },
      { text: "█████████████", color: "#875f00" },
      { text: "██▄█▄", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "███████████████", color: "#875f00" },
      { text: "██▀", color: "#5f3800" },
      { text: "        ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: " ", color: null },
      { text: "████████████▀▀▀▀", color: "#875f00" },
      { text: "         ", color: null },
      { text: "░", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓████████████", color: "#875f00" },
      { text: "            ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓████████████░░░░", color: "#875f00" },
      { text: "      ", color: null },
      { text: "▒", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓█████████████▄▀▄░", color: "#875f00" },
      { text: "   ", color: null },
      { text: "▓", color: "#ffffff" },
      { text: "█", color: "#c0c0c0" },
    ],
    [
      { text: "▓▓▓▓▓▓▓██████", color: "#875f00" },
      { text: "   ", color: null },
      { text: "█████████", color: "#c0c0c0" },
    ],
  ],
];
