/**
 * Commit Message Generator — Server Route
 *
 * POST /api/plugins/site-editor/commit-message
 *
 * Accepts { diff: string } and returns { message: string } generated by Claude Haiku.
 * Uses the Anthropic Messages API directly via fetch (no @ai-sdk/anthropic needed).
 *
 * Requires ANTHROPIC_API_KEY environment variable. Returns { message: "" } if not set.
 */

import type {
  ServerPlugin,
  ServerPluginContext,
} from "@decocms/bindings/server-plugin";

// Extract the Hono app type from the ServerPlugin routes signature
// to avoid a direct `hono` package dependency from the plugin.
type HonoApp = NonNullable<Parameters<NonNullable<ServerPlugin["routes"]>>[0]>;

const ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages";
const HAIKU_MODEL = "claude-haiku-4-5-20251001";
const MAX_TOKENS = 200;

const COMMIT_MESSAGE_PROMPT = `You are a git commit message generator. Generate a single conventional commit message for the following git diff.

Rules:
- Format: <type>(<scope>): <short description>
- Types: feat, fix, chore, docs, style, refactor, perf, test
- Scope: a short noun describing the area changed (e.g., pages, hero, nav, loader)
- Description: imperative, lowercase, no period, max 72 chars total
- Output ONLY the commit message — no explanation, no quotes, no newlines

Examples:
- feat(pages): add hero section with CTA button
- fix(nav): correct mobile menu z-index
- chore(loaders): remove unused product-list loader

Git diff:`;

export function registerCommitMessageRoute(
  app: HonoApp,
  _ctx: ServerPluginContext,
): void {
  app.post("/commit-message", async (c) => {
    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      return c.json({ message: "" }, 200);
    }

    let diff: string;
    try {
      const body = (await c.req.json()) as { diff?: string };
      diff = body.diff ?? "";
    } catch {
      return c.json({ error: "Invalid request body" }, 400);
    }

    // Trim diff to avoid exceeding context limits — Haiku has 200k context but
    // we keep prompts short for speed and cost.
    const trimmedDiff = diff.slice(0, 8000);
    const userMessage = `${COMMIT_MESSAGE_PROMPT}\n\n${trimmedDiff}`;

    try {
      const response = await fetch(ANTHROPIC_API_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model: HAIKU_MODEL,
          max_tokens: MAX_TOKENS,
          messages: [{ role: "user", content: userMessage }],
        }),
      });

      if (!response.ok) {
        console.error(
          "[site-editor] Anthropic API error:",
          response.status,
          await response.text(),
        );
        return c.json({ message: "" }, 200);
      }

      const data = (await response.json()) as {
        content?: Array<{ type: string; text?: string }>;
      };
      const message =
        data.content?.find((b) => b.type === "text")?.text?.trim() ?? "";

      return c.json({ message });
    } catch (err) {
      console.error("[site-editor] Failed to generate commit message:", err);
      return c.json({ message: "" }, 200);
    }
  });
}
