import { COLLECTION_REGISTRY_APP_BULK_CREATE } from "./bulk-create";
import { REGISTRY_AI_GENERATE } from "./ai-generate";
import { COLLECTION_REGISTRY_APP_CREATE } from "./create";
import { COLLECTION_REGISTRY_APP_DELETE } from "./delete";
import { REGISTRY_DISCOVER_TOOLS } from "./discover-tools";
import { COLLECTION_REGISTRY_APP_FILTERS } from "./filters";
import { COLLECTION_REGISTRY_APP_GET } from "./get";
import { COLLECTION_REGISTRY_APP_LIST } from "./list";
import { COLLECTION_REGISTRY_APP_SEARCH } from "./search";
import { COLLECTION_REGISTRY_APP_UPDATE } from "./update";
import { COLLECTION_REGISTRY_APP_VERSIONS } from "./versions";
import { REGISTRY_PUBLISH_REQUEST_LIST } from "./publish-request-list";
import { REGISTRY_PUBLISH_REQUEST_REVIEW } from "./publish-request-review";
import { REGISTRY_PUBLISH_REQUEST_COUNT } from "./publish-request-count";
import { REGISTRY_PUBLISH_REQUEST_DELETE } from "./publish-request-delete";
import { REGISTRY_PUBLISH_API_KEY_GENERATE } from "./publish-api-key-generate";
import { REGISTRY_PUBLISH_API_KEY_LIST } from "./publish-api-key-list";
import { REGISTRY_PUBLISH_API_KEY_REVOKE } from "./publish-api-key-revoke";
import { REGISTRY_TEST_RUN_START } from "./test-run-start";
import { REGISTRY_TEST_RUN_LIST } from "./test-run-list";
import { REGISTRY_TEST_RUN_GET } from "./test-run-get";
import { REGISTRY_TEST_RUN_CANCEL } from "./test-run-cancel";
import { REGISTRY_TEST_RESULT_LIST } from "./test-result-list";
import { REGISTRY_TEST_CONNECTION_LIST } from "./test-connection-list";
import { REGISTRY_TEST_CONNECTION_SYNC } from "./test-connection-sync";
import { REGISTRY_TEST_CONNECTION_UPDATE_AUTH } from "./test-connection-update-auth";

export const tools = [
  COLLECTION_REGISTRY_APP_LIST,
  COLLECTION_REGISTRY_APP_SEARCH,
  COLLECTION_REGISTRY_APP_GET,
  COLLECTION_REGISTRY_APP_VERSIONS,
  COLLECTION_REGISTRY_APP_CREATE,
  COLLECTION_REGISTRY_APP_BULK_CREATE,
  COLLECTION_REGISTRY_APP_UPDATE,
  COLLECTION_REGISTRY_APP_DELETE,
  COLLECTION_REGISTRY_APP_FILTERS,
  REGISTRY_DISCOVER_TOOLS,
  REGISTRY_AI_GENERATE,
  REGISTRY_PUBLISH_REQUEST_LIST,
  REGISTRY_PUBLISH_REQUEST_REVIEW,
  REGISTRY_PUBLISH_REQUEST_COUNT,
  REGISTRY_PUBLISH_REQUEST_DELETE,
  REGISTRY_PUBLISH_API_KEY_GENERATE,
  REGISTRY_PUBLISH_API_KEY_LIST,
  REGISTRY_PUBLISH_API_KEY_REVOKE,
  REGISTRY_TEST_RUN_START,
  REGISTRY_TEST_RUN_LIST,
  REGISTRY_TEST_RUN_GET,
  REGISTRY_TEST_RUN_CANCEL,
  REGISTRY_TEST_RESULT_LIST,
  REGISTRY_TEST_CONNECTION_LIST,
  REGISTRY_TEST_CONNECTION_SYNC,
  REGISTRY_TEST_CONNECTION_UPDATE_AUTH,
];
