import { COLLECTION_REGISTRY_APP_BULK_CREATE } from "./bulk-create";
import { REGISTRY_AI_GENERATE } from "./ai-generate";
import { COLLECTION_REGISTRY_APP_CREATE } from "./create";
import { COLLECTION_REGISTRY_APP_DELETE } from "./delete";
import { REGISTRY_DISCOVER_TOOLS } from "./discover-tools";
import { COLLECTION_REGISTRY_APP_FILTERS } from "./filters";
import { COLLECTION_REGISTRY_APP_GET } from "./get";
import { COLLECTION_REGISTRY_APP_LIST } from "./list";
import { COLLECTION_REGISTRY_APP_UPDATE } from "./update";
import { COLLECTION_REGISTRY_APP_VERSIONS } from "./versions";

export const tools = [
  COLLECTION_REGISTRY_APP_LIST,
  COLLECTION_REGISTRY_APP_GET,
  COLLECTION_REGISTRY_APP_VERSIONS,
  COLLECTION_REGISTRY_APP_CREATE,
  COLLECTION_REGISTRY_APP_BULK_CREATE,
  COLLECTION_REGISTRY_APP_UPDATE,
  COLLECTION_REGISTRY_APP_DELETE,
  COLLECTION_REGISTRY_APP_FILTERS,
  REGISTRY_DISCOVER_TOOLS,
  REGISTRY_AI_GENERATE,
];
