/**
 * Workflows Plugin - Tools Index
 *
 * Exports all MCP tools for the plugin.
 */

import {
  WORKFLOW_COLLECTION_LIST,
  WORKFLOW_COLLECTION_GET,
  WORKFLOW_COLLECTION_CREATE,
  WORKFLOW_COLLECTION_UPDATE,
  WORKFLOW_COLLECTION_DELETE,
} from "./workflow-collection";

import {
  WORKFLOW_EXECUTION_LIST,
  WORKFLOW_EXECUTION_GET,
  WORKFLOW_EXECUTION_CREATE,
  WORKFLOW_EXECUTION_CANCEL,
  WORKFLOW_EXECUTION_RESUME,
  WORKFLOW_EXECUTION_GET_STEP_RESULT,
  WORKFLOW_EXECUTION_GET_WORKFLOW,
} from "./workflow-execution";

export const tools = [
  // Workflow collection CRUD (5)
  WORKFLOW_COLLECTION_LIST,
  WORKFLOW_COLLECTION_GET,
  WORKFLOW_COLLECTION_CREATE,
  WORKFLOW_COLLECTION_UPDATE,
  WORKFLOW_COLLECTION_DELETE,
  // Execution tools (7)
  WORKFLOW_EXECUTION_LIST,
  WORKFLOW_EXECUTION_GET,
  WORKFLOW_EXECUTION_CREATE,
  WORKFLOW_EXECUTION_CANCEL,
  WORKFLOW_EXECUTION_RESUME,
  WORKFLOW_EXECUTION_GET_STEP_RESULT,
  WORKFLOW_EXECUTION_GET_WORKFLOW,
];
